### ISSUE TITLE
Complex usage 

### ISSUE THREAD

**Issue by 2018zhangrrrr** [cran/forestploter#6]
thanks for your contribution to forest plot. I have a request，for complex usage，if my groups are trt1, trt2, trt3, I rechange the example of code by adding another OR/CI into the list. But it seems that the package didn’t separate my groups into 3 levels.what should I do.I’m looking forward to your reply.
/

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
